apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  type: LoadBalancer
  #loadBalancerIP: 跟tom要ip
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
   matchLabels:
    app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: gcr.io/yile-it/aries/server:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: port
          value: ":8080"
      imagePullSecrets:
      - name: docker-pull-cred
