FROM gcr.io/yile-it/base-image:latest

 
MAINTAINER AriesWang

ARG filename
ARG version

ENV File=${filename}_${version}

ADD ${filename} ${File}
ADD run.sh run.sh
RUN chmod +x /${File}
RUN chmod +x /run.sh
ENTRYPOINT ["/run.sh"]

