apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: practice
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: practice
    spec:
      containers:
      - name: practice
        envFrom:
        - configMapRef:
            name: practice
        image: gcr.io/yile-it/scg/practice:32b819fb
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /conf
          name: practice
      volumes:
      - configMap:
          name: practice
        name: practice
