apiVersion: v1
kind: Service
metadata:
  name: practice
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: practice
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080